/* Generated By:JavaCC: Do not edit this line. MiniX10Parser.java */
  public class MiniX10Parser implements MiniX10ParserConstants {

/* We use productions to match >>>, >> and > so that we can keep the
 * type declaration syntax with generics clean
 */


/*************************************
 * The MiniX10 Grammar Starts Here *
 *************************************/
  static final public void File() throws ParseException {
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case CLASS:
      case PUBLIC:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      TopLevelDeclaration();
    }
    jj_consume_token(0);
  }

  static final public void TopLevelDeclaration() throws ParseException {
    if (jj_2_1(12)) {
      MainClass();
    } else if (jj_2_2(2)) {
      ClassDeclaration();
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void MainClass() throws ParseException {
    jj_consume_token(PUBLIC);
    jj_consume_token(CLASS);
    Identifier();
    jj_consume_token(LBRACE);
    jj_consume_token(PUBLIC);
    jj_consume_token(STATIC);
    jj_consume_token(VOID);
    jj_consume_token(MAIN);
    jj_consume_token(LPAREN);
    jj_consume_token(STRING);
    jj_consume_token(LSQPAREN);
    jj_consume_token(RSQPAREN);
    Identifier();
    jj_consume_token(RPAREN);
    jj_consume_token(LBRACE);
    Statement();
    jj_consume_token(RBRACE);
    jj_consume_token(RBRACE);
  }

  static final public void ClassDeclaration() throws ParseException {
    jj_consume_token(CLASS);
    Identifier();
    jj_consume_token(LBRACE);
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PUBLIC:
        ;
        break;
      default:
        jj_la1[1] = jj_gen;
        break label_2;
      }
      ClassMember();
    }
    jj_consume_token(RBRACE);
  }

  static final public void ClassMember() throws ParseException {
    if (jj_2_3(2147483647)) {
      MethodDeclaration();
    } else if (jj_2_4(2)) {
      ConstantDeclaration();
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PUBLIC:
        UpdatableFieldDeclaration();
        break;
      default:
        jj_la1[2] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

  static final public void ConstantDeclaration() throws ParseException {
    jj_consume_token(PUBLIC);
    jj_consume_token(STATIC);
    jj_consume_token(FINAL);
    Type();
    Identifier();
    jj_consume_token(ASSIGN);
    Expression();
    jj_consume_token(SEMICOLON);
  }

  static final public void UpdatableFieldDeclaration() throws ParseException {
    jj_consume_token(PUBLIC);
    Type();
    Identifier();
    jj_consume_token(SEMICOLON);
  }

  static final public void MethodDeclaration() throws ParseException {
    jj_consume_token(PUBLIC);
    ReturnType();
    Identifier();
    jj_consume_token(LPAREN);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case FINAL:
    case BOOLEAN:
    case INTEGER:
    case STRING:
    case DOUBLE:
    case REGION:
    case DIST:
    case PLACE:
    case POINT:
    case IDENTIFIER:
      FormalParameterList();
      break;
    default:
      jj_la1[3] = jj_gen;
      ;
    }
    jj_consume_token(RPAREN);
    Block();
  }

  static final public void FormalParameterList() throws ParseException {
    FormalParameter();
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 124:
        ;
        break;
      default:
        jj_la1[4] = jj_gen;
        break label_3;
      }
      FormalParameterRest();
    }
  }

  static final public void FormalParameter() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case FINAL:
      FinalFormalParameter();
      break;
    case BOOLEAN:
    case INTEGER:
    case STRING:
    case DOUBLE:
    case REGION:
    case DIST:
    case PLACE:
    case POINT:
    case IDENTIFIER:
      UpdatableFormalParameter();
      break;
    default:
      jj_la1[5] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void FinalFormalParameter() throws ParseException {
    jj_consume_token(FINAL);
    Type();
    Identifier();
  }

  static final public void UpdatableFormalParameter() throws ParseException {
    Type();
    Identifier();
  }

  static final public void FormalParameterRest() throws ParseException {
    jj_consume_token(124);
    FormalParameter();
  }

  static final public void ReturnType() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case VOID:
      VoidType();
      break;
    case BOOLEAN:
    case INTEGER:
    case STRING:
    case DOUBLE:
    case REGION:
    case DIST:
    case PLACE:
    case POINT:
    case IDENTIFIER:
      Type();
      break;
    default:
      jj_la1[6] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void VoidType() throws ParseException {
    jj_consume_token(VOID);
  }

  static final public void Type() throws ParseException {
    if (jj_2_5(2147483647)) {
      UpdatableArrayType();
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case BOOLEAN:
      case INTEGER:
      case STRING:
      case DOUBLE:
      case REGION:
      case DIST:
      case PLACE:
      case POINT:
      case IDENTIFIER:
        NonArrayType();
        break;
      default:
        jj_la1[7] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

  static final public void UpdatableArrayType() throws ParseException {
    NonArrayType();
    jj_consume_token(LSQPAREN);
    jj_consume_token(125);
    RankEquation();
    jj_consume_token(RSQPAREN);
  }

  static final public void RankEquation() throws ParseException {
    jj_consume_token(RANK);
    jj_consume_token(126);
    IntegerLiteral();
  }

  static final public void NonArrayType() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case BOOLEAN:
      BooleanType();
      break;
    case INTEGER:
      IntegerType();
      break;
    case DOUBLE:
      DoubleType();
      break;
    case STRING:
      StringType();
      break;
    case PLACE:
      PlaceType();
      break;
    case DIST:
      DistType();
      break;
    case REGION:
      RegionType();
      break;
    case POINT:
      PointType();
      break;
    case IDENTIFIER:
      ClassNameType();
      break;
    default:
      jj_la1[8] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void BooleanType() throws ParseException {
    jj_consume_token(BOOLEAN);
  }

  static final public void IntegerType() throws ParseException {
    jj_consume_token(INTEGER);
  }

  static final public void DoubleType() throws ParseException {
    jj_consume_token(DOUBLE);
  }

  static final public void StringType() throws ParseException {
    jj_consume_token(STRING);
  }

  static final public void PlaceType() throws ParseException {
    jj_consume_token(PLACE);
  }

  static final public void DistType() throws ParseException {
    jj_consume_token(DIST);
    jj_consume_token(LPAREN);
    jj_consume_token(125);
    RankEquation();
    jj_consume_token(RPAREN);
  }

  static final public void RegionType() throws ParseException {
    jj_consume_token(REGION);
    jj_consume_token(LPAREN);
    jj_consume_token(125);
    RankEquation();
    jj_consume_token(RPAREN);
  }

  static final public void PointType() throws ParseException {
    jj_consume_token(POINT);
    jj_consume_token(LPAREN);
    jj_consume_token(125);
    RankEquation();
    jj_consume_token(RPAREN);
  }

  static final public void ClassNameType() throws ParseException {
    Identifier();
  }

  static final public void Identifier() throws ParseException {
    jj_consume_token(IDENTIFIER);
  }

/*
 * Statement syntax follows.
 */
  static final public void Statement() throws ParseException {
    if (jj_2_6(2147483647)) {
      Assignment();
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ASYNC:
        AsyncStatement();
        break;
      case LBRACE:
        Block();
        break;
      case FINISH:
        FinishStatement();
        break;
      case IF:
        IfStatement();
        break;
      case FOR:
        LoopStatement();
        break;
      case LPAREN:
      case LSQPAREN:
      case MINUS:
      case NEW:
      case THIS:
      case FACTORYBlock:
      case MATH:
      case HERE:
      case DISTUNIQUE:
      case INTEGER_LITERAL:
      case FLOATING_POINT_LITERAL:
      case STRING_LITERAL:
      case IDENTIFIER:
        PostfixStatement();
        break;
      case PRINTLN:
        PrintlnStatement();
        break;
      case RETURN:
        ReturnStatement();
        break;
      case THROW:
        ThrowStatement();
        break;
      case WHILE:
        WhileStatement();
        break;
      default:
        jj_la1[9] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

  static final public void Assignment() throws ParseException {
    Expression();
    jj_consume_token(ASSIGN);
    Expression();
    jj_consume_token(SEMICOLON);
  }

  static final public void AsyncStatement() throws ParseException {
    jj_consume_token(ASYNC);
    jj_consume_token(LPAREN);
    Expression();
    jj_consume_token(RPAREN);
    Block();
  }

  static final public void Block() throws ParseException {
    jj_consume_token(LBRACE);
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LPAREN:
      case LSQPAREN:
      case LBRACE:
      case MINUS:
      case FINAL:
      case IF:
      case WHILE:
      case BOOLEAN:
      case INTEGER:
      case NEW:
      case RETURN:
      case STRING:
      case THIS:
      case PRINTLN:
      case FACTORYBlock:
      case THROW:
      case DOUBLE:
      case REGION:
      case DIST:
      case FINISH:
      case MATH:
      case PLACE:
      case POINT:
      case FOR:
      case HERE:
      case DISTUNIQUE:
      case ASYNC:
      case INTEGER_LITERAL:
      case FLOATING_POINT_LITERAL:
      case STRING_LITERAL:
      case IDENTIFIER:
        ;
        break;
      default:
        jj_la1[10] = jj_gen;
        break label_4;
      }
      BlockStatement();
    }
    jj_consume_token(RBRACE);
  }

  static final public void BlockStatement() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case FINAL:
      FinalVariableDeclaration();
      break;
    default:
      jj_la1[11] = jj_gen;
      if (jj_2_7(2147483647)) {
        UpdatableVariableDeclaration();
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case LPAREN:
        case LSQPAREN:
        case LBRACE:
        case MINUS:
        case IF:
        case WHILE:
        case NEW:
        case RETURN:
        case THIS:
        case PRINTLN:
        case FACTORYBlock:
        case THROW:
        case FINISH:
        case MATH:
        case FOR:
        case HERE:
        case DISTUNIQUE:
        case ASYNC:
        case INTEGER_LITERAL:
        case FLOATING_POINT_LITERAL:
        case STRING_LITERAL:
        case IDENTIFIER:
          Statement();
          break;
        default:
          jj_la1[12] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
  }

  static final public void FinalVariableDeclaration() throws ParseException {
    jj_consume_token(FINAL);
    Type();
    Identifier();
    jj_consume_token(ASSIGN);
    Expression();
    jj_consume_token(SEMICOLON);
  }

  static final public void UpdatableVariableDeclaration() throws ParseException {
    Type();
    Identifier();
    jj_consume_token(ASSIGN);
    Expression();
    jj_consume_token(SEMICOLON);
  }

  static final public void FinishStatement() throws ParseException {
    jj_consume_token(FINISH);
    Statement();
  }

  static final public void IfStatement() throws ParseException {
    jj_consume_token(IF);
    jj_consume_token(LPAREN);
    Expression();
    jj_consume_token(RPAREN);
    Statement();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ELSE:
      ElseClause();
      break;
    default:
      jj_la1[13] = jj_gen;
      ;
    }
  }

  static final public void ElseClause() throws ParseException {
    jj_consume_token(ELSE);
    Statement();
  }

  static final public void LoopStatement() throws ParseException {
    jj_consume_token(FOR);
    jj_consume_token(LPAREN);
    PointType();
    ExplodedSpecification();
    jj_consume_token(125);
    Expression();
    jj_consume_token(RPAREN);
    Statement();
  }

  static final public void ExplodedSpecification() throws ParseException {
    IdentifierList();
  }

  static final public void PointName() throws ParseException {
    Identifier();
  }

  static final public void IdentifierList() throws ParseException {
    jj_consume_token(LSQPAREN);
    Identifier();
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 124:
        ;
        break;
      default:
        jj_la1[14] = jj_gen;
        break label_5;
      }
      IdentifierRest();
    }
    jj_consume_token(RSQPAREN);
  }

  static final public void IdentifierRest() throws ParseException {
    jj_consume_token(124);
    Identifier();
  }

  static final public void PostfixStatement() throws ParseException {
    Expression();
    jj_consume_token(SEMICOLON);
  }

  static final public void PrintlnStatement() throws ParseException {
    jj_consume_token(PRINTLN);
    jj_consume_token(LPAREN);
    Expression();
    jj_consume_token(RPAREN);
    jj_consume_token(SEMICOLON);
  }

  static final public void ReturnStatement() throws ParseException {
    jj_consume_token(RETURN);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LPAREN:
    case LSQPAREN:
    case MINUS:
    case NEW:
    case THIS:
    case FACTORYBlock:
    case MATH:
    case HERE:
    case DISTUNIQUE:
    case INTEGER_LITERAL:
    case FLOATING_POINT_LITERAL:
    case STRING_LITERAL:
    case IDENTIFIER:
      Expression();
      break;
    default:
      jj_la1[15] = jj_gen;
      ;
    }
    jj_consume_token(SEMICOLON);
  }

  static final public void ThrowStatement() throws ParseException {
    jj_consume_token(THROW);
    jj_consume_token(NEW);
    jj_consume_token(RUNTIMEEXCEPTION);
    jj_consume_token(LPAREN);
    Expression();
    jj_consume_token(RPAREN);
    jj_consume_token(SEMICOLON);
  }

  static final public void WhileStatement() throws ParseException {
    jj_consume_token(WHILE);
    jj_consume_token(LPAREN);
    Expression();
    jj_consume_token(RPAREN);
    Statement();
  }

/*
 * Expression syntax follows.
 */
  static final public void Expression() throws ParseException {
    if (jj_2_8(2147483647)) {
      InclusiveOrExpression();
    } else if (jj_2_9(2147483647)) {
      EqualsExpression();
    } else if (jj_2_10(2147483647)) {
      NotEqualsExpression();
    } else if (jj_2_11(2147483647)) {
      GreaterThanExpression();
    } else if (jj_2_12(2147483647)) {
      PlusExpression();
    } else if (jj_2_13(2147483647)) {
      MinusExpression();
    } else if (jj_2_14(2147483647)) {
      TimesExpression();
    } else if (jj_2_15(2147483647)) {
      DivideExpression();
    } else if (jj_2_16(3)) {
      SinExpression();
    } else if (jj_2_17(3)) {
      CosExpression();
    } else if (jj_2_18(3)) {
      PowExpression();
    } else if (jj_2_19(3)) {
      AbsExpression();
    } else if (jj_2_20(2147483647)) {
      MapExpression();
    } else if (jj_2_21(2147483647)) {
      RegionConstant();
    } else if (jj_2_22(2147483647)) {
      UnaryMinusExpression();
    } else if (jj_2_23(2147483647)) {
      CoercionToIntExpression();
    } else if (jj_2_24(2147483647)) {
      CoercionToDoubleExpression();
    } else if (jj_2_25(2147483647)) {
      TypeAnnotatedExpression();
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case FACTORYBlock:
        FactoryBlock();
        break;
      default:
        jj_la1[16] = jj_gen;
        if (jj_2_26(2147483647)) {
          ArrayAccess();
        } else if (jj_2_27(2147483647)) {
          DotDistribution();
        } else if (jj_2_28(2147483647)) {
          DotIsFirst();
        } else if (jj_2_29(2147483647)) {
          DotMethodCall();
        } else if (jj_2_30(2147483647)) {
          DotIdentifier();
        } else {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case NEW:
          case THIS:
          case HERE:
          case DISTUNIQUE:
          case INTEGER_LITERAL:
          case FLOATING_POINT_LITERAL:
          case STRING_LITERAL:
          case IDENTIFIER:
            PrimaryExpression();
            break;
          default:
            jj_la1[17] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
        }
      }
    }
  }

  static final public void InclusiveOrExpression() throws ParseException {
    PrimaryExpression();
    jj_consume_token(127);
    Expression();
  }

  static final public void EqualsExpression() throws ParseException {
    PrimaryExpression();
    jj_consume_token(126);
    Expression();
  }

  static final public void NotEqualsExpression() throws ParseException {
    PrimaryExpression();
    jj_consume_token(128);
    Expression();
  }

  static final public void GreaterThanExpression() throws ParseException {
    PrimaryExpression();
    jj_consume_token(GT);
    Expression();
  }

  static final public void PlusExpression() throws ParseException {
    PrimaryExpression();
    jj_consume_token(PLUS);
    Expression();
  }

  static final public void MinusExpression() throws ParseException {
    PrimaryExpression();
    jj_consume_token(MINUS);
    Expression();
  }

  static final public void TimesExpression() throws ParseException {
    PrimaryExpression();
    jj_consume_token(129);
    Expression();
  }

  static final public void DivideExpression() throws ParseException {
    PrimaryExpression();
    jj_consume_token(130);
    Expression();
  }

  static final public void SinExpression() throws ParseException {
    jj_consume_token(MATH);
    jj_consume_token(DOT);
    jj_consume_token(SIN);
    jj_consume_token(LPAREN);
    Expression();
    jj_consume_token(RPAREN);
  }

  static final public void CosExpression() throws ParseException {
    jj_consume_token(MATH);
    jj_consume_token(DOT);
    jj_consume_token(COS);
    jj_consume_token(LPAREN);
    Expression();
    jj_consume_token(RPAREN);
  }

  static final public void PowExpression() throws ParseException {
    jj_consume_token(MATH);
    jj_consume_token(DOT);
    jj_consume_token(POW);
    jj_consume_token(LPAREN);
    Expression();
    jj_consume_token(124);
    Expression();
    jj_consume_token(RPAREN);
  }

  static final public void AbsExpression() throws ParseException {
    jj_consume_token(MATH);
    jj_consume_token(DOT);
    jj_consume_token(ABS);
    jj_consume_token(LPAREN);
    Expression();
    jj_consume_token(RPAREN);
  }

  static final public void MapExpression() throws ParseException {
    PrimaryExpression();
    jj_consume_token(131);
    PrimaryExpression();
  }

  static final public void RegionConstant() throws ParseException {
    jj_consume_token(LSQPAREN);
    ColonExpression();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 124:
      ColonRest();
      break;
    default:
      jj_la1[18] = jj_gen;
      ;
    }
    jj_consume_token(RSQPAREN);
  }

  static final public void ColonRest() throws ParseException {
    jj_consume_token(124);
    ColonExpression();
  }

  static final public void ColonExpression() throws ParseException {
    if (jj_2_31(2147483647)) {
      ColonPair();
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LPAREN:
      case LSQPAREN:
      case MINUS:
      case NEW:
      case THIS:
      case FACTORYBlock:
      case MATH:
      case HERE:
      case DISTUNIQUE:
      case INTEGER_LITERAL:
      case FLOATING_POINT_LITERAL:
      case STRING_LITERAL:
      case IDENTIFIER:
        Expression();
        break;
      default:
        jj_la1[19] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

  static final public void ColonPair() throws ParseException {
    Expression();
    jj_consume_token(125);
    Expression();
  }

  static final public void UnaryMinusExpression() throws ParseException {
    jj_consume_token(MINUS);
    PrimaryExpression();
  }

  static final public void CoercionToIntExpression() throws ParseException {
    jj_consume_token(LPAREN);
    jj_consume_token(INTEGER);
    jj_consume_token(RPAREN);
    Expression();
  }

  static final public void CoercionToDoubleExpression() throws ParseException {
    jj_consume_token(LPAREN);
    jj_consume_token(DOUBLE);
    jj_consume_token(RPAREN);
    Expression();
  }

  static final public void TypeAnnotatedExpression() throws ParseException {
    jj_consume_token(LPAREN);
    TypeAnnotation();
    jj_consume_token(RPAREN);
    Expression();
  }

  static final public void TypeAnnotation() throws ParseException {
    if (jj_2_32(2147483647)) {
      UpdatableArrayType();
    } else if (jj_2_33(2147483647)) {
      DistType();
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void PrimaryExpression() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case HERE:
    case DISTUNIQUE:
    case INTEGER_LITERAL:
    case FLOATING_POINT_LITERAL:
    case STRING_LITERAL:
      Literal();
      break;
    case THIS:
      This();
      break;
    case NEW:
      AllocationExpression();
      break;
    case IDENTIFIER:
      Identifier();
      break;
    default:
      jj_la1[20] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void This() throws ParseException {
    jj_consume_token(THIS);
  }

  static final public void FactoryBlock() throws ParseException {
    jj_consume_token(FACTORYBlock);
    jj_consume_token(LPAREN);
    Expression();
    jj_consume_token(RPAREN);
  }

  static final public void ArrayAccess() throws ParseException {
    PrimaryExpression();
    jj_consume_token(LSQPAREN);
    ExpressionList();
    jj_consume_token(RSQPAREN);
  }

  static final public void DotMethodCall() throws ParseException {
    PrimaryExpression();
    jj_consume_token(DOT);
    Identifier();
    jj_consume_token(LPAREN);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LPAREN:
    case LSQPAREN:
    case MINUS:
    case NEW:
    case THIS:
    case FACTORYBlock:
    case MATH:
    case HERE:
    case DISTUNIQUE:
    case INTEGER_LITERAL:
    case FLOATING_POINT_LITERAL:
    case STRING_LITERAL:
    case IDENTIFIER:
      ExpressionList();
      break;
    default:
      jj_la1[21] = jj_gen;
      ;
    }
    jj_consume_token(RPAREN);
  }

  static final public void DotDistribution() throws ParseException {
    PrimaryExpression();
    jj_consume_token(DOT);
    jj_consume_token(DISTRIBUTION);
  }

  static final public void DotIsFirst() throws ParseException {
    PrimaryExpression();
    jj_consume_token(DOT);
    jj_consume_token(ISFIRST);
    jj_consume_token(LPAREN);
    jj_consume_token(RPAREN);
  }

  static final public void DotIdentifier() throws ParseException {
    PrimaryExpression();
    jj_consume_token(DOT);
    Identifier();
  }

  static final public void AllocationExpression() throws ParseException {
    if (jj_2_34(3)) {
      NewObject();
    } else if (jj_2_35(2147483647)) {
      NewUpdatableArray();
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void NewObject() throws ParseException {
    jj_consume_token(NEW);
    Identifier();
    jj_consume_token(LPAREN);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LPAREN:
    case LSQPAREN:
    case MINUS:
    case NEW:
    case THIS:
    case FACTORYBlock:
    case MATH:
    case HERE:
    case DISTUNIQUE:
    case INTEGER_LITERAL:
    case FLOATING_POINT_LITERAL:
    case STRING_LITERAL:
    case IDENTIFIER:
      ExpressionList();
      break;
    default:
      jj_la1[22] = jj_gen;
      ;
    }
    jj_consume_token(RPAREN);
  }

  static final public void NewUpdatableArray() throws ParseException {
    jj_consume_token(NEW);
    NonArrayType();
    jj_consume_token(LSQPAREN);
    Identifier();
    jj_consume_token(RSQPAREN);
    if (jj_2_36(2147483647)) {
      ArrayInitializer();
    } else {
      ;
    }
  }

  static final public void Literal() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INTEGER_LITERAL:
      IntegerLiteral();
      break;
    case FLOATING_POINT_LITERAL:
      FloatingPointLiteral();
      break;
    case STRING_LITERAL:
      StringLiteral();
      break;
    case HERE:
      HereLiteral();
      break;
    case DISTUNIQUE:
      DistUnique();
      break;
    default:
      jj_la1[23] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void IntegerLiteral() throws ParseException {
    jj_consume_token(INTEGER_LITERAL);
  }

  static final public void FloatingPointLiteral() throws ParseException {
    jj_consume_token(FLOATING_POINT_LITERAL);
  }

  static final public void StringLiteral() throws ParseException {
    jj_consume_token(STRING_LITERAL);
  }

  static final public void HereLiteral() throws ParseException {
    jj_consume_token(HERE);
  }

  static final public void DistUnique() throws ParseException {
    jj_consume_token(DISTUNIQUE);
  }

  static final public void ExpressionList() throws ParseException {
    Expression();
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 124:
        ;
        break;
      default:
        jj_la1[24] = jj_gen;
        break label_6;
      }
      ArgumentRest();
    }
  }

  static final public void ArgumentRest() throws ParseException {
    jj_consume_token(124);
    Expression();
  }

  static final public void ArrayInitializer() throws ParseException {
    jj_consume_token(LPAREN);
    PointType();
    ExplodedSpecification();
    jj_consume_token(RPAREN);
    Block();
  }

  static private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  static private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  static private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  static private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  static private boolean jj_2_5(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  static private boolean jj_2_6(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_6(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  static private boolean jj_2_7(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_7(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  static private boolean jj_2_8(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_8(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  static private boolean jj_2_9(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_9(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  static private boolean jj_2_10(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_10(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(9, xla); }
  }

  static private boolean jj_2_11(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_11(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(10, xla); }
  }

  static private boolean jj_2_12(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_12(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(11, xla); }
  }

  static private boolean jj_2_13(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_13(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(12, xla); }
  }

  static private boolean jj_2_14(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_14(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(13, xla); }
  }

  static private boolean jj_2_15(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_15(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(14, xla); }
  }

  static private boolean jj_2_16(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_16(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(15, xla); }
  }

  static private boolean jj_2_17(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_17(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(16, xla); }
  }

  static private boolean jj_2_18(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_18(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(17, xla); }
  }

  static private boolean jj_2_19(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_19(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(18, xla); }
  }

  static private boolean jj_2_20(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_20(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(19, xla); }
  }

  static private boolean jj_2_21(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_21(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(20, xla); }
  }

  static private boolean jj_2_22(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_22(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(21, xla); }
  }

  static private boolean jj_2_23(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_23(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(22, xla); }
  }

  static private boolean jj_2_24(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_24(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(23, xla); }
  }

  static private boolean jj_2_25(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_25(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(24, xla); }
  }

  static private boolean jj_2_26(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_26(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(25, xla); }
  }

  static private boolean jj_2_27(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_27(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(26, xla); }
  }

  static private boolean jj_2_28(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_28(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(27, xla); }
  }

  static private boolean jj_2_29(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_29(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(28, xla); }
  }

  static private boolean jj_2_30(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_30(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(29, xla); }
  }

  static private boolean jj_2_31(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_31(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(30, xla); }
  }

  static private boolean jj_2_32(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_32(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(31, xla); }
  }

  static private boolean jj_2_33(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_33(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(32, xla); }
  }

  static private boolean jj_2_34(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_34(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(33, xla); }
  }

  static private boolean jj_2_35(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_35(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(34, xla); }
  }

  static private boolean jj_2_36(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_36(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(35, xla); }
  }

  static private boolean jj_3R_17() {
    if (jj_scan_token(MATH)) return true;
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(POW)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_29()) return true;
    if (jj_scan_token(124)) return true;
    if (jj_3R_29()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  static private boolean jj_3R_35() {
    if (jj_scan_token(RANK)) return true;
    if (jj_scan_token(126)) return true;
    if (jj_scan_token(108)) return true;
    return false;
  }

  static private boolean jj_3R_16() {
    if (jj_scan_token(MATH)) return true;
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(COS)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_29()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  static private boolean jj_3_5() {
    if (jj_3R_11()) return true;
    return false;
  }

  static private boolean jj_3R_11() {
    if (jj_3R_32()) return true;
    if (jj_scan_token(LSQPAREN)) return true;
    if (jj_scan_token(125)) return true;
    if (jj_3R_35()) return true;
    if (jj_scan_token(RSQPAREN)) return true;
    return false;
  }

  static private boolean jj_3R_15() {
    if (jj_scan_token(MATH)) return true;
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(SIN)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_29()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  static private boolean jj_3R_37() {
    if (jj_3R_32()) return true;
    return false;
  }

  static private boolean jj_3R_87() {
    if (jj_3R_14()) return true;
    if (jj_scan_token(130)) return true;
    if (jj_3R_29()) return true;
    return false;
  }

  static private boolean jj_3R_36() {
    if (jj_3R_11()) return true;
    return false;
  }

  static private boolean jj_3R_13() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_36()) {
    jj_scanpos = xsp;
    if (jj_3R_37()) return true;
    }
    return false;
  }

  static private boolean jj_3R_86() {
    if (jj_3R_14()) return true;
    if (jj_scan_token(129)) return true;
    if (jj_3R_29()) return true;
    return false;
  }

  static private boolean jj_3R_85() {
    if (jj_3R_14()) return true;
    if (jj_scan_token(MINUS)) return true;
    if (jj_3R_29()) return true;
    return false;
  }

  static private boolean jj_3R_34() {
    if (jj_3R_13()) return true;
    return false;
  }

  static private boolean jj_3R_9() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(32)) {
    jj_scanpos = xsp;
    if (jj_3R_34()) return true;
    }
    return false;
  }

  static private boolean jj_3R_84() {
    if (jj_3R_14()) return true;
    if (jj_scan_token(PLUS)) return true;
    if (jj_3R_29()) return true;
    return false;
  }

  static private boolean jj_3R_83() {
    if (jj_3R_14()) return true;
    if (jj_scan_token(GT)) return true;
    if (jj_3R_29()) return true;
    return false;
  }

  static private boolean jj_3R_82() {
    if (jj_3R_14()) return true;
    if (jj_scan_token(128)) return true;
    if (jj_3R_29()) return true;
    return false;
  }

  static private boolean jj_3R_81() {
    if (jj_3R_14()) return true;
    if (jj_scan_token(126)) return true;
    if (jj_3R_29()) return true;
    return false;
  }

  static private boolean jj_3_30() {
    if (jj_3R_28()) return true;
    return false;
  }

  static private boolean jj_3R_80() {
    if (jj_3R_14()) return true;
    if (jj_scan_token(127)) return true;
    if (jj_3R_29()) return true;
    return false;
  }

  static private boolean jj_3_29() {
    if (jj_3R_27()) return true;
    return false;
  }

  static private boolean jj_3_28() {
    if (jj_3R_26()) return true;
    return false;
  }

  static private boolean jj_3R_65() {
    if (jj_3R_14()) return true;
    return false;
  }

  static private boolean jj_3_27() {
    if (jj_3R_25()) return true;
    return false;
  }

  static private boolean jj_3R_64() {
    if (jj_3R_28()) return true;
    return false;
  }

  static private boolean jj_3_26() {
    if (jj_3R_24()) return true;
    return false;
  }

  static private boolean jj_3R_63() {
    if (jj_3R_27()) return true;
    return false;
  }

  static private boolean jj_3_25() {
    if (jj_3R_23()) return true;
    return false;
  }

  static private boolean jj_3R_62() {
    if (jj_3R_26()) return true;
    return false;
  }

  static private boolean jj_3_24() {
    if (jj_3R_22()) return true;
    return false;
  }

  static private boolean jj_3R_61() {
    if (jj_3R_25()) return true;
    return false;
  }

  static private boolean jj_3_23() {
    if (jj_3R_21()) return true;
    return false;
  }

  static private boolean jj_3R_60() {
    if (jj_3R_24()) return true;
    return false;
  }

  static private boolean jj_3R_59() {
    if (jj_3R_89()) return true;
    return false;
  }

  static private boolean jj_3R_10() {
    if (jj_scan_token(PUBLIC)) return true;
    if (jj_scan_token(STATIC)) return true;
    return false;
  }

  static private boolean jj_3_3() {
    if (jj_scan_token(PUBLIC)) return true;
    if (jj_3R_9()) return true;
    if (jj_scan_token(118)) return true;
    if (jj_scan_token(LPAREN)) return true;
    return false;
  }

  static private boolean jj_3_22() {
    if (jj_3R_20()) return true;
    return false;
  }

  static private boolean jj_3R_58() {
    if (jj_3R_23()) return true;
    return false;
  }

  static private boolean jj_3_21() {
    if (jj_3R_19()) return true;
    return false;
  }

  static private boolean jj_3R_57() {
    if (jj_3R_22()) return true;
    return false;
  }

  static private boolean jj_3_20() {
    if (jj_3R_14()) return true;
    if (jj_scan_token(131)) return true;
    return false;
  }

  static private boolean jj_3R_56() {
    if (jj_3R_21()) return true;
    return false;
  }

  static private boolean jj_3_4() {
    if (jj_3R_10()) return true;
    return false;
  }

  static private boolean jj_3R_55() {
    if (jj_3R_20()) return true;
    return false;
  }

  static private boolean jj_3R_54() {
    if (jj_3R_19()) return true;
    return false;
  }

  static private boolean jj_3R_8() {
    if (jj_scan_token(CLASS)) return true;
    if (jj_scan_token(118)) return true;
    return false;
  }

  static private boolean jj_3R_53() {
    if (jj_3R_88()) return true;
    return false;
  }

  static private boolean jj_3_19() {
    if (jj_3R_18()) return true;
    return false;
  }

  static private boolean jj_3_15() {
    if (jj_3R_14()) return true;
    if (jj_scan_token(130)) return true;
    return false;
  }

  static private boolean jj_3_18() {
    if (jj_3R_17()) return true;
    return false;
  }

  static private boolean jj_3_14() {
    if (jj_3R_14()) return true;
    if (jj_scan_token(129)) return true;
    return false;
  }

  static private boolean jj_3_17() {
    if (jj_3R_16()) return true;
    return false;
  }

  static private boolean jj_3R_7() {
    if (jj_scan_token(PUBLIC)) return true;
    if (jj_scan_token(CLASS)) return true;
    if (jj_scan_token(118)) return true;
    if (jj_scan_token(LBRACE)) return true;
    if (jj_scan_token(PUBLIC)) return true;
    if (jj_scan_token(STATIC)) return true;
    if (jj_scan_token(VOID)) return true;
    if (jj_scan_token(MAIN)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_scan_token(STRING)) return true;
    if (jj_scan_token(LSQPAREN)) return true;
    if (jj_scan_token(RSQPAREN)) return true;
    return false;
  }

  static private boolean jj_3_13() {
    if (jj_3R_14()) return true;
    if (jj_scan_token(MINUS)) return true;
    return false;
  }

  static private boolean jj_3_16() {
    if (jj_3R_15()) return true;
    return false;
  }

  static private boolean jj_3_12() {
    if (jj_3R_14()) return true;
    if (jj_scan_token(PLUS)) return true;
    return false;
  }

  static private boolean jj_3R_52() {
    if (jj_3R_87()) return true;
    return false;
  }

  static private boolean jj_3_11() {
    if (jj_3R_14()) return true;
    if (jj_scan_token(GT)) return true;
    return false;
  }

  static private boolean jj_3_2() {
    if (jj_3R_8()) return true;
    return false;
  }

  static private boolean jj_3R_51() {
    if (jj_3R_86()) return true;
    return false;
  }

  static private boolean jj_3_10() {
    if (jj_3R_14()) return true;
    if (jj_scan_token(128)) return true;
    return false;
  }

  static private boolean jj_3_1() {
    if (jj_3R_7()) return true;
    return false;
  }

  static private boolean jj_3R_50() {
    if (jj_3R_85()) return true;
    return false;
  }

  static private boolean jj_3_9() {
    if (jj_3R_14()) return true;
    if (jj_scan_token(126)) return true;
    return false;
  }

  static private boolean jj_3R_49() {
    if (jj_3R_84()) return true;
    return false;
  }

  static private boolean jj_3_8() {
    if (jj_3R_14()) return true;
    if (jj_scan_token(127)) return true;
    return false;
  }

  static private boolean jj_3R_48() {
    if (jj_3R_83()) return true;
    return false;
  }

  static private boolean jj_3R_47() {
    if (jj_3R_82()) return true;
    return false;
  }

  static private boolean jj_3R_46() {
    if (jj_3R_81()) return true;
    return false;
  }

  static private boolean jj_3R_29() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_45()) {
    jj_scanpos = xsp;
    if (jj_3R_46()) {
    jj_scanpos = xsp;
    if (jj_3R_47()) {
    jj_scanpos = xsp;
    if (jj_3R_48()) {
    jj_scanpos = xsp;
    if (jj_3R_49()) {
    jj_scanpos = xsp;
    if (jj_3R_50()) {
    jj_scanpos = xsp;
    if (jj_3R_51()) {
    jj_scanpos = xsp;
    if (jj_3R_52()) {
    jj_scanpos = xsp;
    if (jj_3_16()) {
    jj_scanpos = xsp;
    if (jj_3_17()) {
    jj_scanpos = xsp;
    if (jj_3_18()) {
    jj_scanpos = xsp;
    if (jj_3_19()) {
    jj_scanpos = xsp;
    if (jj_3R_53()) {
    jj_scanpos = xsp;
    if (jj_3R_54()) {
    jj_scanpos = xsp;
    if (jj_3R_55()) {
    jj_scanpos = xsp;
    if (jj_3R_56()) {
    jj_scanpos = xsp;
    if (jj_3R_57()) {
    jj_scanpos = xsp;
    if (jj_3R_58()) {
    jj_scanpos = xsp;
    if (jj_3R_59()) {
    jj_scanpos = xsp;
    if (jj_3R_60()) {
    jj_scanpos = xsp;
    if (jj_3R_61()) {
    jj_scanpos = xsp;
    if (jj_3R_62()) {
    jj_scanpos = xsp;
    if (jj_3R_63()) {
    jj_scanpos = xsp;
    if (jj_3R_64()) {
    jj_scanpos = xsp;
    if (jj_3R_65()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_45() {
    if (jj_3R_80()) return true;
    return false;
  }

  static private boolean jj_3R_127() {
    if (jj_scan_token(WHILE)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_29()) return true;
    if (jj_scan_token(RPAREN)) return true;
    if (jj_3R_107()) return true;
    return false;
  }

  static private boolean jj_3R_129() {
    if (jj_3R_29()) return true;
    return false;
  }

  static private boolean jj_3R_126() {
    if (jj_scan_token(THROW)) return true;
    if (jj_scan_token(NEW)) return true;
    if (jj_scan_token(RUNTIMEEXCEPTION)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_29()) return true;
    if (jj_scan_token(RPAREN)) return true;
    if (jj_scan_token(SEMICOLON)) return true;
    return false;
  }

  static private boolean jj_3R_125() {
    if (jj_scan_token(RETURN)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_129()) jj_scanpos = xsp;
    if (jj_scan_token(SEMICOLON)) return true;
    return false;
  }

  static private boolean jj_3R_96() {
    if (jj_3R_99()) return true;
    return false;
  }

  static private boolean jj_3R_124() {
    if (jj_scan_token(PRINTLN)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_29()) return true;
    if (jj_scan_token(RPAREN)) return true;
    if (jj_scan_token(SEMICOLON)) return true;
    return false;
  }

  static private boolean jj_3R_79() {
    if (jj_3R_95()) return true;
    return false;
  }

  static private boolean jj_3R_123() {
    if (jj_3R_29()) return true;
    if (jj_scan_token(SEMICOLON)) return true;
    return false;
  }

  static private boolean jj_3R_33() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_69()) return true;
    if (jj_3R_70()) return true;
    if (jj_scan_token(RPAREN)) return true;
    if (jj_3R_71()) return true;
    return false;
  }

  static private boolean jj_3R_99() {
    if (jj_scan_token(124)) return true;
    if (jj_scan_token(118)) return true;
    return false;
  }

  static private boolean jj_3R_95() {
    if (jj_scan_token(124)) return true;
    if (jj_3R_29()) return true;
    return false;
  }

  static private boolean jj_3R_91() {
    if (jj_scan_token(LSQPAREN)) return true;
    if (jj_scan_token(118)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_96()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(RSQPAREN)) return true;
    return false;
  }

  static private boolean jj_3R_43() {
    if (jj_3R_29()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_79()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_70() {
    if (jj_3R_91()) return true;
    return false;
  }

  static private boolean jj_3R_122() {
    if (jj_scan_token(FOR)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_69()) return true;
    if (jj_3R_70()) return true;
    if (jj_scan_token(125)) return true;
    if (jj_3R_29()) return true;
    if (jj_scan_token(RPAREN)) return true;
    if (jj_3R_107()) return true;
    return false;
  }

  static private boolean jj_3R_130() {
    if (jj_scan_token(ELSE)) return true;
    if (jj_3R_107()) return true;
    return false;
  }

  static private boolean jj_3R_128() {
    if (jj_3R_130()) return true;
    return false;
  }

  static private boolean jj_3R_121() {
    if (jj_scan_token(IF)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_29()) return true;
    if (jj_scan_token(RPAREN)) return true;
    if (jj_3R_107()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_128()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3R_103() {
    if (jj_3R_43()) return true;
    return false;
  }

  static private boolean jj_3_36() {
    if (jj_3R_33()) return true;
    return false;
  }

  static private boolean jj_3R_120() {
    if (jj_scan_token(FINISH)) return true;
    if (jj_3R_107()) return true;
    return false;
  }

  static private boolean jj_3R_72() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(108)) {
    jj_scanpos = xsp;
    if (jj_scan_token(114)) {
    jj_scanpos = xsp;
    if (jj_scan_token(117)) {
    jj_scanpos = xsp;
    if (jj_scan_token(102)) {
    jj_scanpos = xsp;
    if (jj_scan_token(103)) return true;
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_106() {
    if (jj_3R_13()) return true;
    if (jj_scan_token(118)) return true;
    if (jj_scan_token(ASSIGN)) return true;
    if (jj_3R_29()) return true;
    if (jj_scan_token(SEMICOLON)) return true;
    return false;
  }

  static private boolean jj_3R_44() {
    if (jj_3R_43()) return true;
    return false;
  }

  static private boolean jj_3R_104() {
    if (jj_3R_33()) return true;
    return false;
  }

  static private boolean jj_3_7() {
    if (jj_3R_13()) return true;
    if (jj_scan_token(118)) return true;
    if (jj_scan_token(ASSIGN)) return true;
    return false;
  }

  static private boolean jj_3R_98() {
    if (jj_scan_token(NEW)) return true;
    if (jj_3R_32()) return true;
    if (jj_scan_token(LSQPAREN)) return true;
    if (jj_scan_token(118)) return true;
    if (jj_scan_token(RSQPAREN)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_104()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3_35() {
    if (jj_scan_token(NEW)) return true;
    if (jj_3R_32()) return true;
    if (jj_scan_token(LSQPAREN)) return true;
    return false;
  }

  static private boolean jj_3R_105() {
    if (jj_scan_token(FINAL)) return true;
    if (jj_3R_13()) return true;
    if (jj_scan_token(118)) return true;
    if (jj_scan_token(ASSIGN)) return true;
    if (jj_3R_29()) return true;
    if (jj_scan_token(SEMICOLON)) return true;
    return false;
  }

  static private boolean jj_3R_31() {
    if (jj_scan_token(NEW)) return true;
    if (jj_scan_token(118)) return true;
    if (jj_scan_token(LPAREN)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_103()) jj_scanpos = xsp;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  static private boolean jj_3R_102() {
    if (jj_3R_107()) return true;
    return false;
  }

  static private boolean jj_3R_101() {
    if (jj_3R_106()) return true;
    return false;
  }

  static private boolean jj_3R_93() {
    if (jj_3R_98()) return true;
    return false;
  }

  static private boolean jj_3R_92() {
    if (jj_3R_97()) return true;
    return false;
  }

  static private boolean jj_3R_97() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_100()) {
    jj_scanpos = xsp;
    if (jj_3R_101()) {
    jj_scanpos = xsp;
    if (jj_3R_102()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3R_100() {
    if (jj_3R_105()) return true;
    return false;
  }

  static private boolean jj_3_34() {
    if (jj_3R_31()) return true;
    return false;
  }

  static private boolean jj_3R_73() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_34()) {
    jj_scanpos = xsp;
    if (jj_3R_93()) return true;
    }
    return false;
  }

  static private boolean jj_3R_71() {
    if (jj_scan_token(LBRACE)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_92()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(RBRACE)) return true;
    return false;
  }

  static private boolean jj_3R_28() {
    if (jj_3R_14()) return true;
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(118)) return true;
    return false;
  }

  static private boolean jj_3R_119() {
    if (jj_scan_token(ASYNC)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_29()) return true;
    if (jj_scan_token(RPAREN)) return true;
    if (jj_3R_71()) return true;
    return false;
  }

  static private boolean jj_3R_26() {
    if (jj_3R_14()) return true;
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(ISFIRST)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  static private boolean jj_3R_12() {
    if (jj_3R_29()) return true;
    if (jj_scan_token(ASSIGN)) return true;
    if (jj_3R_29()) return true;
    if (jj_scan_token(SEMICOLON)) return true;
    return false;
  }

  static private boolean jj_3R_25() {
    if (jj_3R_14()) return true;
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(DISTRIBUTION)) return true;
    return false;
  }

  static private boolean jj_3R_118() {
    if (jj_3R_127()) return true;
    return false;
  }

  static private boolean jj_3R_117() {
    if (jj_3R_126()) return true;
    return false;
  }

  static private boolean jj_3R_27() {
    if (jj_3R_14()) return true;
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(118)) return true;
    if (jj_scan_token(LPAREN)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_44()) jj_scanpos = xsp;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  static private boolean jj_3R_116() {
    if (jj_3R_125()) return true;
    return false;
  }

  static private boolean jj_3R_115() {
    if (jj_3R_124()) return true;
    return false;
  }

  static private boolean jj_3R_114() {
    if (jj_3R_123()) return true;
    return false;
  }

  static private boolean jj_3R_24() {
    if (jj_3R_14()) return true;
    if (jj_scan_token(LSQPAREN)) return true;
    if (jj_3R_43()) return true;
    if (jj_scan_token(RSQPAREN)) return true;
    return false;
  }

  static private boolean jj_3R_113() {
    if (jj_3R_122()) return true;
    return false;
  }

  static private boolean jj_3_6() {
    if (jj_3R_12()) return true;
    return false;
  }

  static private boolean jj_3R_112() {
    if (jj_3R_121()) return true;
    return false;
  }

  static private boolean jj_3R_111() {
    if (jj_3R_120()) return true;
    return false;
  }

  static private boolean jj_3R_89() {
    if (jj_scan_token(FACTORYBlock)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_29()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  static private boolean jj_3R_110() {
    if (jj_3R_71()) return true;
    return false;
  }

  static private boolean jj_3R_109() {
    if (jj_3R_119()) return true;
    return false;
  }

  static private boolean jj_3R_108() {
    if (jj_3R_12()) return true;
    return false;
  }

  static private boolean jj_3R_107() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_108()) {
    jj_scanpos = xsp;
    if (jj_3R_109()) {
    jj_scanpos = xsp;
    if (jj_3R_110()) {
    jj_scanpos = xsp;
    if (jj_3R_111()) {
    jj_scanpos = xsp;
    if (jj_3R_112()) {
    jj_scanpos = xsp;
    if (jj_3R_113()) {
    jj_scanpos = xsp;
    if (jj_3R_114()) {
    jj_scanpos = xsp;
    if (jj_3R_115()) {
    jj_scanpos = xsp;
    if (jj_3R_116()) {
    jj_scanpos = xsp;
    if (jj_3R_117()) {
    jj_scanpos = xsp;
    if (jj_3R_118()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3_33() {
    if (jj_3R_30()) return true;
    return false;
  }

  static private boolean jj_3_32() {
    if (jj_3R_11()) return true;
    return false;
  }

  static private boolean jj_3R_39() {
    if (jj_3R_73()) return true;
    return false;
  }

  static private boolean jj_3R_38() {
    if (jj_3R_72()) return true;
    return false;
  }

  static private boolean jj_3R_14() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_38()) {
    jj_scanpos = xsp;
    if (jj_scan_token(50)) {
    jj_scanpos = xsp;
    if (jj_3R_39()) {
    jj_scanpos = xsp;
    if (jj_scan_token(118)) return true;
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_78() {
    if (jj_3R_30()) return true;
    return false;
  }

  static private boolean jj_3R_42() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_77()) {
    jj_scanpos = xsp;
    if (jj_3R_78()) return true;
    }
    return false;
  }

  static private boolean jj_3R_77() {
    if (jj_3R_11()) return true;
    return false;
  }

  static private boolean jj_3R_69() {
    if (jj_scan_token(POINT)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_scan_token(125)) return true;
    if (jj_3R_35()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  static private boolean jj_3R_23() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_42()) return true;
    if (jj_scan_token(RPAREN)) return true;
    if (jj_3R_29()) return true;
    return false;
  }

  static private boolean jj_3R_90() {
    if (jj_scan_token(REGION)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_scan_token(125)) return true;
    if (jj_3R_35()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  static private boolean jj_3R_22() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_scan_token(DOUBLE)) return true;
    if (jj_scan_token(RPAREN)) return true;
    if (jj_3R_29()) return true;
    return false;
  }

  static private boolean jj_3R_30() {
    if (jj_scan_token(DIST)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_scan_token(125)) return true;
    if (jj_3R_35()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  static private boolean jj_3R_21() {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_scan_token(INTEGER)) return true;
    if (jj_scan_token(RPAREN)) return true;
    if (jj_3R_29()) return true;
    return false;
  }

  static private boolean jj_3R_20() {
    if (jj_scan_token(MINUS)) return true;
    if (jj_3R_14()) return true;
    return false;
  }

  static private boolean jj_3R_41() {
    if (jj_3R_76()) return true;
    return false;
  }

  static private boolean jj_3_31() {
    if (jj_3R_29()) return true;
    if (jj_scan_token(125)) return true;
    return false;
  }

  static private boolean jj_3R_94() {
    if (jj_3R_29()) return true;
    if (jj_scan_token(125)) return true;
    if (jj_3R_29()) return true;
    return false;
  }

  static private boolean jj_3R_75() {
    if (jj_3R_29()) return true;
    return false;
  }

  static private boolean jj_3R_40() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_74()) {
    jj_scanpos = xsp;
    if (jj_3R_75()) return true;
    }
    return false;
  }

  static private boolean jj_3R_74() {
    if (jj_3R_94()) return true;
    return false;
  }

  static private boolean jj_3R_76() {
    if (jj_scan_token(124)) return true;
    if (jj_3R_40()) return true;
    return false;
  }

  static private boolean jj_3R_19() {
    if (jj_scan_token(LSQPAREN)) return true;
    if (jj_3R_40()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_41()) jj_scanpos = xsp;
    if (jj_scan_token(RSQPAREN)) return true;
    return false;
  }

  static private boolean jj_3R_68() {
    if (jj_3R_69()) return true;
    return false;
  }

  static private boolean jj_3R_67() {
    if (jj_3R_90()) return true;
    return false;
  }

  static private boolean jj_3R_66() {
    if (jj_3R_30()) return true;
    return false;
  }

  static private boolean jj_3R_88() {
    if (jj_3R_14()) return true;
    if (jj_scan_token(131)) return true;
    if (jj_3R_14()) return true;
    return false;
  }

  static private boolean jj_3R_18() {
    if (jj_scan_token(MATH)) return true;
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(ABS)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_29()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  static private boolean jj_3R_32() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(33)) {
    jj_scanpos = xsp;
    if (jj_scan_token(34)) {
    jj_scanpos = xsp;
    if (jj_scan_token(66)) {
    jj_scanpos = xsp;
    if (jj_scan_token(49)) {
    jj_scanpos = xsp;
    if (jj_scan_token(87)) {
    jj_scanpos = xsp;
    if (jj_3R_66()) {
    jj_scanpos = xsp;
    if (jj_3R_67()) {
    jj_scanpos = xsp;
    if (jj_3R_68()) {
    jj_scanpos = xsp;
    if (jj_scan_token(118)) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public MiniX10ParserTokenManager token_source;
  static JavaCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[25];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static private int[] jj_la1_3;
  static private int[] jj_la1_4;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
      jj_la1_init_2();
      jj_la1_init_3();
      jj_la1_init_4();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x1000000,0x0,0x0,0x4000000,0x0,0x4000000,0x0,0x0,0x0,0x88102a00,0x8c102a00,0x4000000,0x88102a00,0x10000000,0x0,0x100a00,0x0,0x0,0x0,0x100a00,0x0,0x100a00,0x100a00,0x0,0x0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x4000,0x4000,0x4000,0x20006,0x0,0x20006,0x20007,0x20006,0x20006,0x40c8008,0x40e800e,0x0,0x40c8008,0x0,0x0,0x4040008,0x4000000,0x40008,0x0,0x4040008,0x40008,0x4040008,0x4040008,0x0,0x0,};
   }
   private static void jj_la1_init_2() {
      jj_la1_2 = new int[] {0x0,0x0,0x0,0x800844,0x0,0x800844,0x800844,0x800844,0x800844,0x14001,0x814845,0x0,0x14001,0x0,0x0,0x10000,0x0,0x0,0x0,0x10000,0x0,0x10000,0x10000,0x0,0x0,};
   }
   private static void jj_la1_init_3() {
      jj_la1_3 = new int[] {0x0,0x0,0x0,0x400002,0x10000000,0x400002,0x400002,0x400002,0x400002,0x6412e0,0x6412e2,0x0,0x6412e0,0x0,0x10000000,0x6410c0,0x0,0x6410c0,0x10000000,0x6410c0,0x6410c0,0x6410c0,0x6410c0,0x2410c0,0x10000000,};
   }
   private static void jj_la1_init_4() {
      jj_la1_4 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
   }
  static final private JJCalls[] jj_2_rtns = new JJCalls[36];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

  /** Constructor with InputStream. */
  public MiniX10Parser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public MiniX10Parser(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new JavaCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new MiniX10ParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 25; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 25; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public MiniX10Parser(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new JavaCharStream(stream, 1, 1);
    token_source = new MiniX10ParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 25; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 25; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public MiniX10Parser(MiniX10ParserTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 25; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(MiniX10ParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 25; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  static final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  static private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[132];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 25; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
          if ((jj_la1_2[i] & (1<<j)) != 0) {
            la1tokens[64+j] = true;
          }
          if ((jj_la1_3[i] & (1<<j)) != 0) {
            la1tokens[96+j] = true;
          }
          if ((jj_la1_4[i] & (1<<j)) != 0) {
            la1tokens[128+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 132; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

  static private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 36; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
            case 5: jj_3_6(); break;
            case 6: jj_3_7(); break;
            case 7: jj_3_8(); break;
            case 8: jj_3_9(); break;
            case 9: jj_3_10(); break;
            case 10: jj_3_11(); break;
            case 11: jj_3_12(); break;
            case 12: jj_3_13(); break;
            case 13: jj_3_14(); break;
            case 14: jj_3_15(); break;
            case 15: jj_3_16(); break;
            case 16: jj_3_17(); break;
            case 17: jj_3_18(); break;
            case 18: jj_3_19(); break;
            case 19: jj_3_20(); break;
            case 20: jj_3_21(); break;
            case 21: jj_3_22(); break;
            case 22: jj_3_23(); break;
            case 23: jj_3_24(); break;
            case 24: jj_3_25(); break;
            case 25: jj_3_26(); break;
            case 26: jj_3_27(); break;
            case 27: jj_3_28(); break;
            case 28: jj_3_29(); break;
            case 29: jj_3_30(); break;
            case 30: jj_3_31(); break;
            case 31: jj_3_32(); break;
            case 32: jj_3_33(); break;
            case 33: jj_3_34(); break;
            case 34: jj_3_35(); break;
            case 35: jj_3_36(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  static private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

                              }
