/* Generated by JTB 1.4.4 */
package syntaxtree;

import visitor.*;

public class FinalVariableDeclaration implements INode {

  public NodeToken f0;

  public Type f1;

  public Identifier f2;

  public NodeToken f3;

  public Expression f4;

  public NodeToken f5;

  private static final long serialVersionUID = 144L;

  public FinalVariableDeclaration(final NodeToken n0, final Type n1, final Identifier n2, final NodeToken n3, final Expression n4, final NodeToken n5) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
    f4 = n4;
    f5 = n5;
  }

  public FinalVariableDeclaration(final Type n0, final Identifier n1, final Expression n2) {
    f0 = new NodeToken("final");
    f1 = n0;
    f2 = n1;
    f3 = new NodeToken("=");
    f4 = n2;
    f5 = new NodeToken(";");
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
