/* Generated by JTB 1.4.4 */
package syntaxtree;

import visitor.*;

public class LoopStatement implements INode {

  public NodeToken f0;

  public NodeToken f1;

  public PointType f2;

  public ExplodedSpecification f3;

  public NodeToken f4;

  public Expression f5;

  public NodeToken f6;

  public Statement f7;

  private static final long serialVersionUID = 144L;

  public LoopStatement(final NodeToken n0, final NodeToken n1, final PointType n2, final ExplodedSpecification n3, final NodeToken n4, final Expression n5, final NodeToken n6, final Statement n7) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
    f4 = n4;
    f5 = n5;
    f6 = n6;
    f7 = n7;
  }

  public LoopStatement(final PointType n0, final ExplodedSpecification n1, final Expression n2, final Statement n3) {
    f0 = new NodeToken("for");
    f1 = new NodeToken("(");
    f2 = n0;
    f3 = n1;
    f4 = new NodeToken(":");
    f5 = n2;
    f6 = new NodeToken(")");
    f7 = n3;
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
