/* Generated by JTB 1.4.4 */
package syntaxtree;

import visitor.*;

public class MethodDeclaration implements INode {

  public NodeToken f0;

  public ReturnType f1;

  public Identifier f2;

  public NodeToken f3;

  public NodeOptional f4;

  public NodeToken f5;

  public Block f6;

  private static final long serialVersionUID = 144L;

  public MethodDeclaration(final NodeToken n0, final ReturnType n1, final Identifier n2, final NodeToken n3, final NodeOptional n4, final NodeToken n5, final Block n6) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
    f4 = n4;
    f5 = n5;
    f6 = n6;
  }

  public MethodDeclaration(final ReturnType n0, final Identifier n1, final NodeOptional n2, final Block n3) {
    f0 = new NodeToken("public");
    f1 = n0;
    f2 = n1;
    f3 = new NodeToken("(");
    f4 = n2;
    f5 = new NodeToken(")");
    f6 = n3;
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
