/* Generated by JTB 1.4.4 */
package syntaxtree;

import visitor.*;

public class RankEquation implements INode {

  public NodeToken f0;

  public NodeToken f1;

  public IntegerLiteral f2;

  private static final long serialVersionUID = 144L;

  public RankEquation(final NodeToken n0, final NodeToken n1, final IntegerLiteral n2) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
  }

  public RankEquation(final IntegerLiteral n0) {
    f0 = new NodeToken("rank");
    f1 = new NodeToken("==");
    f2 = n0;
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
